name: qiskit-env

channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy=1.26.4
  - leidenalg
  - igraph
  - scipy
  - scanpy
  - pandas
  - matplotlib
  - scikit-learn
  - qiskit=1.3
  - qiskit-ibm-runtime
  - qiskit[visualization]
  - ipykernel
  - pytorch 
  - torchvision 
  - torchaudio
  - pylatexenc
  - ipywidgets
  - pip
  - pip:
    - magic-imputation
    - qiskit_aer