# Author: Selim Romero, Texas A&M University

"""
Permutation and bootstrap testing for QUBO-based differential co-expression analysis.

This module provides statistical validation procedures for gene selection in
QUBO-optimized differential co-expression subnetworks, including label
permutation tests for significance and bootstrap stability analysis.
"""

import warnings
import numpy as np
from sklearn.preprocessing import normalize
from sklearn.metrics import roc_auc_score

try:
    import matplotlib.pyplot as plt
    import seaborn as sns
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False

try:
    from tqdm import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False


def permutation_test(X, g, batch_id, selected_idx, Q1, condition_A='KO', condition_B='WT',
                     n_perm=1000, seed=42, verbose=True):
    """
    Label permutation test for differential co-expression subnetwork significance.

    Tests the null hypothesis that the selected gene set's differential
    co-expression pattern is not significantly different from random label
    assignment. The test computes the energy of the selected genes on a
    null distribution of differential co-expression matrices generated by
    randomly permuting condition labels.

    Parameters
    ----------
    X : array-like, shape (N, G)
        Expression matrix (cells × genes). Can be sparse.
    g : array-like, shape (G,)
        Gene names (strings).
    batch_id : array-like, shape (N,)
        Condition labels for each cell (strings).
    selected_idx : array-like, shape (K,)
        Indices of selected genes (0-indexed into g).
    Q1 : array-like, shape (K, K)
        QUBO quadratic interaction matrix for selected genes.
        Usually difference of co-expression matrices: Q1 = Sb - Sa.
    condition_A : str, default='KO'
        Condition A label (substring search in batch_id).
    condition_B : str, default='WT'
        Condition B label (substring search in batch_id).
    n_perm : int, default=1000
        Number of permutations to perform.
    seed : int, default=42
        Random seed for reproducibility.
    verbose : bool, default=True
        If True, print progress information.

    Returns
    -------
    dict
        Dictionary with keys:
        - 'pval': float
            Permutation p-value. Fraction of null energies <= real energy
            (for minimization: pval = mean(E_null <= E_real)).
        - 'zscore': float
            Z-score of real energy relative to null: (E_real - mean(E_null)) / std(E_null).
        - 'E_real': float
            Energy of selected genes on real differential co-expression.
        - 'E_null': np.ndarray, shape (n_perm,)
            Null distribution of energies (one per permutation).
        - 'null_mean': float
            Mean of null energy distribution.
        - 'null_std': float
            Standard deviation of null energy distribution.
        - 'effect_size': float
            Effect size (Cohen's d): (E_real - null_mean) / null_std.
        - 'significance_label': str
            Star annotation: '***' (p<0.001), '**' (p<0.01), '*' (p<0.05), 'n.s.'.

    Notes
    -----
    Algorithm:
    1. Compute real differential co-expression matrix: Xdiff = Xb - Xa
       where Xa, Xb are normalized (L2, axis=1) expression in conditions A, B.
    2. Compute real energy: E_real = z^T @ Q1 @ z, where z = selected_idx.astype(float).
    3. For each permutation:
       a. Shuffle batch_id labels randomly.
       b. Re-extract condition A and B cells based on shuffled labels.
       c. Recompute differential co-expression matrix on permuted data.
       d. Compute energy of selected genes on permuted matrix.
    4. Compute p-value as fraction of E_null <= E_real.
    5. Compute z-score and effect size.

    References
    ----------
    Permutation testing is a standard nonparametric hypothesis testing approach
    for assessing significance of observed statistics under random label
    assignment.

    Examples
    --------
    >>> X = np.random.poisson(2, (500, 100))
    >>> genes = [f'Gene_{i}' for i in range(100)]
    >>> batch = ['KO'] * 250 + ['WT'] * 250
    >>> selected = np.array([0, 5, 10, 15, 20])
    >>> Q1 = np.random.randn(5, 5)
    >>> Q1 = (Q1 + Q1.T) / 2  # Symmetric
    >>> result = permutation_test(X, genes, batch, selected, Q1, n_perm=100)
    >>> print(f"p-value: {result['pval']:.4f}, z-score: {result['zscore']:.2f}")
    """
    batch_id = np.asarray(batch_id)
    X = np.asarray(X)
    selected_idx = np.asarray(selected_idx, dtype=int)
    Q1 = np.asarray(Q1)

    if verbose:
        print(f"Permutation test: {n_perm} permutations, seed={seed}")

    # Extract real condition masks
    condition_A_mask = np.array([condition_A.lower() in str(b).lower() for b in batch_id])
    condition_B_mask = np.array([condition_B.lower() in str(b).lower() for b in batch_id])

    Xa_real = X[condition_A_mask, :]
    Xb_real = X[condition_B_mask, :]

    # Compute real differential co-expression
    Za_real = normalize(Xa_real, norm='l2', axis=1)
    Zb_real = normalize(Xb_real, norm='l2', axis=1)
    Sa_real = Za_real @ Za_real.T
    Sb_real = Zb_real @ Zb.T
    Xdiff_real = Sb_real - Sa_real

    # Real energy
    bz = selected_idx.astype(float)
    E_real = bz @ Q1 @ bz

    # Null distribution
    E_null = np.zeros(n_perm)

    rng = np.random.default_rng(seed)

    # Progress bar setup
    if HAS_TQDM:
        iterator = tqdm(range(n_perm), desc="Permutations", disable=not verbose)
    else:
        iterator = range(n_perm)
        if verbose:
            print(f"Running {n_perm} permutations...")

    for perm_idx in iterator:
        # Shuffle batch labels
        shuffled_batch = rng.permutation(batch_id)

        # Extract condition A and B from shuffled labels
        shuffled_A_mask = np.array([condition_A.lower() in str(b).lower() for b in shuffled_batch])
        shuffled_B_mask = np.array([condition_B.lower() in str(b).lower() for b in shuffled_batch])

        Xa_perm = X[shuffled_A_mask, :]
        Xb_perm = X[shuffled_B_mask, :]

        # Recompute differential co-expression
        if Xa_perm.shape[0] > 0 and Xb_perm.shape[0] > 0:
            Za_perm = normalize(Xa_perm, norm='l2', axis=1)
            Zb_perm = normalize(Xb_perm, norm='l2', axis=1)
            Sa_perm = Za_perm @ Za_perm.T
            Sb_perm = Zb_perm @ Zb_perm.T
            Xdiff_perm = Sb_perm - Sa_perm

            # Energy on permuted data
            E_null[perm_idx] = bz @ Xdiff_perm @ bz
        else:
            E_null[perm_idx] = np.nan

        # Manual progress reporting (fallback if tqdm unavailable)
        if not HAS_TQDM and verbose and (perm_idx + 1) % 100 == 0:
            print(f"  Completed {perm_idx + 1}/{n_perm} permutations")

    # Remove NaN values
    E_null_valid = E_null[~np.isnan(E_null)]

    # Compute statistics
    null_mean = np.mean(E_null_valid)
    null_std = np.std(E_null_valid)

    # P-value (for minimization: how many permuted energies <= real)
    pval = np.mean(E_null_valid <= E_real)

    # Z-score
    if null_std > 0:
        zscore = (E_real - null_mean) / null_std
    else:
        zscore = np.nan

    # Effect size (Cohen's d)
    effect_size = zscore

    # Significance label
    if pval < 0.001:
        significance_label = '***'
    elif pval < 0.01:
        significance_label = '**'
    elif pval < 0.05:
        significance_label = '*'
    else:
        significance_label = 'n.s.'

    if verbose:
        print(f"  p-value: {pval:.4f} ({significance_label})")
        print(f"  z-score: {zscore:.3f}")
        print(f"  E_real: {E_real:.4f}, E_null: mean={null_mean:.4f}, std={null_std:.4f}")

    return {
        'pval': pval,
        'zscore': zscore,
        'E_real': E_real,
        'E_null': E_null_valid,
        'null_mean': null_mean,
        'null_std': null_std,
        'effect_size': effect_size,
        'significance_label': significance_label,
    }


def bootstrap_stability(X, g, batch_id, genelist, K, condition_A='KO', condition_B='WT',
                        method='mnn', n_neighbors=30, n_svd=50, n_boot=200, seed=42,
                        freq_thresh=0.5, verbose=True):
    """
    Bootstrap cell resampling for gene selection stability analysis.

    Assesses the stability of gene selection by repeatedly resampling cells
    (with replacement) within each condition, re-optimizing the QUBO problem,
    and recording which genes are consistently selected across bootstrap samples.

    Parameters
    ----------
    X : array-like, shape (N, G)
        Expression matrix (cells × genes). Can be sparse.
    g : array-like, shape (G,)
        Gene names (strings).
    batch_id : array-like, shape (N,)
        Condition labels for each cell (strings).
    genelist : array-like, shape (G,)
        Gene names in the pathway (strings).
    K : int
        Number of genes to select in each bootstrap iteration.
    condition_A : str, default='KO'
        Condition A label (substring search in batch_id).
    condition_B : str, default='WT'
        Condition B label (substring search in batch_id).
    method : str, default='mnn'
        Graph construction method ('mnn' for mutual nearest neighbors).
    n_neighbors : int, default=30
        Number of neighbors for graph construction.
    n_svd : int, default=50
        Dimension for SVD preprocessing.
    n_boot : int, default=200
        Number of bootstrap iterations.
    seed : int, default=42
        Random seed for reproducibility.
    freq_thresh : float, default=0.5
        Frequency threshold for calling a gene "stable" (0-1).
    verbose : bool, default=True
        If True, print progress information.

    Returns
    -------
    dict
        Dictionary with keys:
        - 'gene_frequency': np.ndarray, shape (G,)
            Selection frequency for each gene (0-1, across all bootstrap iterations).
        - 'stability_index': float
            Mean selection frequency among genes with freq > freq_thresh.
            Measures overall stability (higher = more stable).
        - 'freq_matrix': np.ndarray, shape (n_successful, G)
            Binary matrix: each row is a bootstrap iteration, 1 if gene selected.
        - 'stable_genes': np.ndarray
            Gene names with selection frequency > freq_thresh.
        - 'gene_names': np.ndarray
            All gene names in the pathway (same as input genelist).
        - 'n_successful': int
            Number of successful bootstrap iterations (some may fail).
        - 'freq_thresh': float
            Frequency threshold used.

    Notes
    -----
    Algorithm:
    1. For each bootstrap iteration:
       a. Resample cells with replacement within each condition separately.
       b. Recompute similarity matrices (co-expression) on resampled cells.
       c. Build MNN adjacency graph.
       d. Build pathway network (correlation, correlation cutoff).
       e. Assemble QUBO matrix (quadratic + linear terms).
       f. Solve with simulated annealing (num_reads=100 for speed).
       g. Record binary selection vector.
    2. Compute gene selection frequency (mean of freq_matrix along axis=0).
    3. Identify stable genes (frequency > freq_thresh).
    4. Compute stability index (mean of frequencies for stable genes).

    This function assumes imports from qubo_dr.graph and qubo_dr.qubo modules:
    - from qubo_dr.graph import build_mnn_adjacency
    - from qubo_dr.qubo import build_pathway_network, assemble_qubo, solve_qubo

    Requires: scikit-learn, numpy, scipy, dimod (for QUBO solving).

    Examples
    --------
    >>> X = np.random.poisson(2, (500, 100))
    >>> genes = [f'Gene_{i}' for i in range(100)]
    >>> pathway = genes[:20]
    >>> batch = ['KO'] * 250 + ['WT'] * 250
    >>> result = bootstrap_stability(X, genes, batch, pathway, K=10, n_boot=50)
    >>> print(f"Stable genes: {len(result['stable_genes'])}")
    >>> print(f"Stability index: {result['stability_index']:.3f}")
    """
    # Import from qubo_dr submodules
    try:
        from qubo_dr.graph import build_mnn_adjacency
        from qubo_dr.qubo import build_pathway_network, assemble_qubo, solve_qubo
    except ImportError as e:
        raise ImportError(
            f"Required qubo_dr modules not found: {e}. "
            "Ensure qubo_dr.graph and qubo_dr.qubo are installed."
        )

    X = np.asarray(X)
    batch_id = np.asarray(batch_id)
    genelist = np.asarray(genelist)

    if verbose:
        print(f"Bootstrap stability: {n_boot} iterations, K={K}, freq_thresh={freq_thresh}")

    rng = np.random.default_rng(seed)

    # Extract real condition masks for cell indices
    condition_A_mask = np.array([condition_A.lower() in str(b).lower() for b in batch_id])
    condition_B_mask = np.array([condition_B.lower() in str(b).lower() for b in batch_id])

    idx_a = np.where(condition_A_mask)[0]
    idx_b = np.where(condition_B_mask)[0]

    freq_matrix = []
    n_successful = 0

    # Progress bar setup
    if HAS_TQDM:
        iterator = tqdm(range(n_boot), desc="Bootstrap", disable=not verbose)
    else:
        iterator = range(n_boot)
        if verbose:
            print(f"Running {n_boot} bootstrap iterations...")

    for boot_idx in iterator:
        try:
            # Resample cells with replacement within each condition
            boot_idx_a = rng.choice(idx_a, size=len(idx_a), replace=True)
            boot_idx_b = rng.choice(idx_b, size=len(idx_b), replace=True)

            boot_idx_all = np.concatenate([boot_idx_a, boot_idx_b])
            X_boot = X[boot_idx_all, :]
            batch_boot = np.concatenate([
                np.full(len(boot_idx_a), condition_A),
                np.full(len(boot_idx_b), condition_B)
            ])

            # Recompute similarity matrices (co-expression)
            Za = normalize(X_boot[np.array([condition_A.lower() in str(b).lower() for b in batch_boot]), :],
                          norm='l2', axis=1)
            Zb = normalize(X_boot[np.array([condition_B.lower() in str(b).lower() for b in batch_boot]), :],
                          norm='l2', axis=1)

            Sa = Za @ Za.T
            Sb = Zb @ Zb.T

            # Build MNN adjacency (graph-based differential co-expression)
            # Note: This assumes build_mnn_adjacency can work with similarity matrices
            # Adjust as needed for your implementation
            try:
                G_adj = build_mnn_adjacency(X_boot, n_neighbors=n_neighbors)
            except Exception:
                # Fallback: use SVD + kNN if MNN fails
                from sklearn.decomposition import TruncatedSVD
                from sklearn.neighbors import NearestNeighbors

                svd = TruncatedSVD(n_components=min(n_svd, X_boot.shape[0] - 1))
                X_svd = svd.fit_transform(X_boot)
                nbrs = NearestNeighbors(n_neighbors=n_neighbors).fit(X_svd)
                _, indices = nbrs.kneighbors(X_svd)
                G_adj = np.zeros((X_boot.shape[0], X_boot.shape[0]))
                for i, neighbors in enumerate(indices):
                    G_adj[i, neighbors] = 1

            # Build pathway network
            W_path = build_pathway_network(genelist, method='correlation')

            # Assemble QUBO
            Q_boot = assemble_qubo(Sa, Sb, W_path, K=K)

            # Solve QUBO (faster with fewer reads for bootstrap)
            solution = solve_qubo(Q_boot, num_reads=100, num_sweeps=1000, seed=seed + boot_idx)

            # Extract selected genes
            selected = np.array(solution)
            freq_matrix.append(selected)
            n_successful += 1

        except Exception as e:
            if verbose and boot_idx % 50 == 0:
                warnings.warn(f"Bootstrap iteration {boot_idx} failed: {e}", UserWarning)
            continue

        # Manual progress reporting (fallback)
        if not HAS_TQDM and verbose and (boot_idx + 1) % 50 == 0:
            print(f"  Completed {boot_idx + 1}/{n_boot} bootstrap iterations ({n_successful} successful)")

    if n_successful == 0:
        raise RuntimeError("All bootstrap iterations failed. Check input data and parameters.")

    # Convert to array and compute frequencies
    freq_matrix = np.array(freq_matrix)  # (n_successful, G)
    gene_frequency = freq_matrix.mean(axis=0)  # (G,)

    # Identify stable genes
    stable_genes = genelist[gene_frequency > freq_thresh]

    # Stability index
    if len(stable_genes) > 0:
        stability_index = gene_frequency[gene_frequency > freq_thresh].mean()
    else:
        stability_index = 0.0

    if verbose:
        print(f"  {n_successful}/{n_boot} successful bootstrap iterations")
        print(f"  {len(stable_genes)} stable genes (freq > {freq_thresh})")
        print(f"  Stability index: {stability_index:.3f}")

    return {
        'gene_frequency': gene_frequency,
        'stability_index': stability_index,
        'freq_matrix': freq_matrix,
        'stable_genes': stable_genes,
        'gene_names': genelist,
        'n_successful': n_successful,
        'freq_thresh': freq_thresh,
    }


def plot_permutation_null(E_real, E_null, pval, zscore, ax=None, title='Permutation Test'):
    """
    Plot null energy distribution from permutation test.

    Creates a histogram of null energies with the observed (real) energy marked
    as a vertical dashed line. Includes statistical annotations (z-score, p-value).

    Parameters
    ----------
    E_real : float
        Real energy value observed.
    E_null : array-like, shape (n_perm,)
        Null distribution of energies from permutation test.
    pval : float
        P-value from permutation test.
    zscore : float
        Z-score of real energy relative to null.
    ax : matplotlib.axes.Axes, optional
        Axis object to plot on. If None, creates new figure.
    title : str, default='Permutation Test'
        Plot title.

    Returns
    -------
    fig : matplotlib.figure.Figure
        Figure object.
    ax : matplotlib.axes.Axes
        Axes object.

    Notes
    -----
    The plot shows:
    - Histogram of null energies (counts).
    - Vertical dashed red line at E_real.
    - Shaded rejection region (typically p < 0.05).
    - Text annotation with z-score and p-value.
    """
    if not HAS_MATPLOTLIB:
        raise ImportError("matplotlib and seaborn are required for plotting. "
                          "Install with: pip install matplotlib seaborn")

    E_null = np.asarray(E_null)

    if ax is None:
        fig, ax = plt.subplots(figsize=(10, 6))
    else:
        fig = ax.get_figure()

    # Histogram of null distribution
    ax.hist(E_null, bins=30, color='steelblue', alpha=0.7, edgecolor='black', label='Null distribution')

    # Mark real energy
    ax.axvline(E_real, color='red', linestyle='--', linewidth=2.5, label=f'Real energy: {E_real:.3f}')

    # Shade rejection region (p < 0.05 tail)
    quantile_05 = np.percentile(E_null, 5)
    ax.axvline(quantile_05, color='orange', linestyle=':', linewidth=2, alpha=0.7, label='5% quantile')

    # Add text annotation
    textstr = f'Z-score: {zscore:.3f}\nP-value: {pval:.4f}'
    ax.text(0.98, 0.97, textstr, transform=ax.transAxes, fontsize=11,
            verticalalignment='top', horizontalalignment='right',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

    ax.set_xlabel('Energy')
    ax.set_ylabel('Frequency')
    ax.set_title(title)
    ax.legend(loc='upper left')
    ax.grid(axis='y', alpha=0.3)

    return fig, ax


def plot_gene_frequency(gene_frequency, gene_names, selected_idx=None, freq_thresh=0.5,
                        top_n=30, ax=None):
    """
    Create a horizontal bar chart of gene selection frequencies from bootstrap analysis.

    Parameters
    ----------
    gene_frequency : array-like, shape (G,)
        Selection frequency for each gene (0-1).
    gene_names : array-like, shape (G,)
        Gene names corresponding to frequencies.
    selected_idx : array-like, optional
        Indices of genes selected in the real analysis (for highlighting).
    freq_thresh : float, default=0.5
        Frequency threshold for significance (vertical dashed line).
    top_n : int, default=30
        Number of top genes to display (by frequency).
    ax : matplotlib.axes.Axes, optional
        Axis object to plot on. If None, creates new figure.

    Returns
    -------
    fig : matplotlib.figure.Figure
        Figure object.
    ax : matplotlib.axes.Axes
        Axes object.

    Notes
    -----
    The plot shows:
    - Horizontal bars for top_n genes by selection frequency.
    - Color gradient: gray (low frequency) to deep blue (high frequency).
    - Vertical dashed line at freq_thresh.
    - Genes in selected_idx highlighted with a distinct border (if provided).
    """
    if not HAS_MATPLOTLIB:
        raise ImportError("matplotlib and seaborn are required for plotting. "
                          "Install with: pip install matplotlib seaborn")

    gene_frequency = np.asarray(gene_frequency)
    gene_names = np.asarray(gene_names)

    # Sort by frequency and select top_n
    sorted_idx = np.argsort(gene_frequency)[::-1][:top_n]
    top_freqs = gene_frequency[sorted_idx]
    top_names = gene_names[sorted_idx]

    # Identify which top genes are in selected_idx
    highlight_mask = np.zeros(len(sorted_idx), dtype=bool)
    if selected_idx is not None:
        selected_idx = np.asarray(selected_idx)
        highlight_mask = np.isin(sorted_idx, selected_idx)

    if ax is None:
        fig, ax = plt.subplots(figsize=(10, 8))
    else:
        fig = ax.get_figure()

    # Color by frequency (gradient)
    colors = plt.cm.RdYlBu_r(top_freqs)

    # Create horizontal bar chart
    y_pos = np.arange(len(top_names))
    bars = ax.barh(y_pos, top_freqs, color=colors, edgecolor='black', linewidth=0.5)

    # Highlight selected genes
    if selected_idx is not None:
        for i, bar in enumerate(bars):
            if highlight_mask[i]:
                bar.set_linewidth(2)
                bar.set_edgecolor('darkgreen')

    # Add frequency threshold line
    ax.axvline(freq_thresh, color='red', linestyle='--', linewidth=2, alpha=0.7,
               label=f'Threshold: {freq_thresh}')

    # Labels and formatting
    ax.set_yticks(y_pos)
    ax.set_yticklabels(top_names, fontsize=9)
    ax.set_xlabel('Selection Frequency', fontsize=11)
    ax.set_title(f'Gene Selection Frequency (Top {top_n})', fontsize=12)
    ax.set_xlim(0, 1.0)
    ax.grid(axis='x', alpha=0.3)
    ax.legend()

    # Invert y-axis so highest frequency is at top
    ax.invert_yaxis()

    return fig, ax
